# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Debi < Formula
  desc "Command-line interface for the Debi API"
  homepage "https://debi.pro"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/debipro/cli/releases/download/v0.1.4/debi_0.1.4_mac-os_x86_64.tar.gz"
      sha256 "af75c16e1a2f2a2225b69efe34f83a0c1854c63a319767c79aae11306ecf1d3a"

      define_method(:install) do
        bin.install "debi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/debipro/cli/releases/download/v0.1.4/debi_0.1.4_mac-os_arm64.tar.gz"
      sha256 "12c6569eeaf0be4ae771c624789aa40c490f64cc0490a6cb099253c08390b15e"

      define_method(:install) do
        bin.install "debi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/debipro/cli/releases/download/v0.1.4/debi_0.1.4_linux_x86_64.tar.gz"
      sha256 "6a4383c77a99dedbe89db0304ea207f448e56878ffc80c8e5f3c8609e357fb76"
      define_method(:install) do
        bin.install "debi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/debipro/cli/releases/download/v0.1.4/debi_0.1.4_linux_arm64.tar.gz"
      sha256 "bdd14045665af8591597fac9efa3cb8fef315e037fd2c6b9db52fc1843e7d7d1"
      define_method(:install) do
        bin.install "debi"
      end
    end
  end

  test do
    assert_match "debi", shell_output("#{bin}/debi version")
  end
end
