# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Debi < Formula
  desc "Command-line interface for the Debi API"
  homepage "https://debi.pro"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/debipro/cli/releases/download/v0.1.7/debi_0.1.7_mac-os_x86_64.tar.gz"
      sha256 "3226150e78545adc9a3b9ab0c79a77dc0a029ce42d34d625f633965c2f209bcd"

      define_method(:install) do
        bin.install "debi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/debipro/cli/releases/download/v0.1.7/debi_0.1.7_mac-os_arm64.tar.gz"
      sha256 "4fff918f426d7deff0ec0b83fd402b88e71d924d0e258a45842b4ed43adb1bc9"

      define_method(:install) do
        bin.install "debi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/debipro/cli/releases/download/v0.1.7/debi_0.1.7_linux_x86_64.tar.gz"
      sha256 "52fd10480bd514dee0e33ffd8ccaed92b89b42fc86e1ea00b8832b3d9ba469db"
      define_method(:install) do
        bin.install "debi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/debipro/cli/releases/download/v0.1.7/debi_0.1.7_linux_arm64.tar.gz"
      sha256 "59a250e69c0e5a9b6039900e6ac2fc9e46038e9d5c17a87350de7048a23c9eed"
      define_method(:install) do
        bin.install "debi"
      end
    end
  end

  test do
    assert_match "debi", shell_output("#{bin}/debi version")
  end
end
